services:

  frontend:
      build:
        context: ./frontend
      ports:
        - 8080:8080
      depends_on:
        users:
          condition: service_healthy
  users:
    build:
      context: ./users
    ports:
      - 8001:8001
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    # user: postgres
    # secrets:
    #   - db-password
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=example_app
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=secret
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready -U example -d users" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:


